# Generated by Django 5.2.8 on 2026-06-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='score_pronunciation',
            new_name='score_overall',
        ),
    ]
