# Generated by Django 5.2.8 on 2026-06-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_rename_score_pronunciation_message_score_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='score_pronunciation',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
