# Generated by Django 5.2.8 on 2026-07-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_remove_message_score_pronunciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='counts_for_stats',
            field=models.BooleanField(default=True),
        ),
    ]
