# Generated by Django 5.2.8 on 2026-07-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0005_message_counts_for_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cerebras_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cohere_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openrouter_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('cerebras', 'Cerebras'), ('cohere', 'Cohere')], default='gemini', max_length=20),
        ),
    ]
