# Generated by Django 5.2.8 on 2026-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_userprofile_cerebras_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cohere_api_key',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('cerebras', 'Cerebras')], default='gemini', max_length=20),
        ),
    ]
