# Generated by Django 5.2.8 on 2026-07-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_remove_userprofile_cohere_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='message',
            name='ai_provider_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
