# Generated by Django 5.2.8 on 2026-07-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_message_ai_model_name_message_ai_provider_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cerebras_api_key',
            new_name='chatgpt_api_key',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('openrouter', 'OpenRouter'), ('chatgpt', 'ChatGPT')], default='gemini', max_length=20),
        ),
    ]
