# Generated by Django 5.2.8 on 2026-07-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_rename_cerebras_api_key_userprofile_chatgpt_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='chatgpt_api_key',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('groq', 'Groq'), ('openrouter', 'OpenRouter')], default='gemini', max_length=20),
        ),
    ]
