# Generated by Django 5.2.8 on 2026-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_remove_userprofile_chatgpt_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gemini_api_key_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groq_api_key_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groq_api_key_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openrouter_api_key_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openrouter_api_key_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
