# Generated by Django 5.2.8 on 2026-07-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_userprofile_gemini_api_key_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='explanation_language',
            field=models.CharField(choices=[('en', 'English'), ('bn', 'Bengali')], default='en', max_length=5),
        ),
    ]
