# Generated by Django 5.2.8 on 2026-07-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_userprofile_explanation_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='daily_word_goal',
            field=models.IntegerField(default=250),
        ),
    ]
