# Generated by Django 5.2.8 on 2026-07-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_alter_userprofile_daily_word_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='score_confidence',
        ),
        migrations.AddField(
            model_name='message',
            name='score_expression',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='score_mechanics',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
