# Generated by Django 5.2.8 on 2026-07-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0014_remove_message_score_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_key_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_api_key_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='openai_model',
            field=models.CharField(blank=True, default='gpt-4o', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('groq', 'Groq'), ('openrouter', 'OpenRouter')], default='gemini', max_length=20),
        ),
    ]
