# Generated by Django 5.2.8 on 2026-07-17 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_userprofile_openai_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='gemini_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gemini_api_key_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gemini_api_key_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groq_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groq_api_key_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groq_api_key_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_api_key_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openai_api_key_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openrouter_api_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openrouter_api_key_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='openrouter_api_key_3',
        ),
    ]
