"""
Django settings for Uccharon project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.core.exceptions import ImproperlyConfigured
from django.core.management.utils import get_random_secret_key
from csp.constants import NONE, SELF, NONCE
from dotenv import load_dotenv
import dj_database_url


load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Reads from environment so DEBUG is True locally but False on Railway.
DEBUG = os.getenv("DEBUG", "False") == "True"

# SECURITY WARNING: keep the secret key used in production secret!
# The key MUST come from the environment. There is intentionally NO hardcoded
# fallback: a committed key is public and would let an attacker forge session
# cookies and signed tokens (account takeover).
#   • Production (DEBUG=False): fail fast if SECRET_KEY is missing/blank.
#   • Development (DEBUG=True): generate a random ephemeral key so local runs
#     work without a .env. It changes each start (sessions won't persist across
#     restarts), which is fine for development and never used in production.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = get_random_secret_key()
    else:
        raise ImproperlyConfigured(
            "The SECRET_KEY environment variable is required when DEBUG is False. "
            "Set a strong, unique SECRET_KEY in the production environment."
        )


ALLOWED_HOSTS = [
    "uccharon.up.railway.app",
    "127.0.0.1",
    "localhost",
]

# Required when running behind a proxy (Railway) that terminates HTTPS.
# Without this, request.is_secure() returns False even on real HTTPS requests,
# which breaks CSRF cookies, secure redirects, and admin login.
CSRF_TRUSTED_ORIGINS = [
    "https://uccharon.up.railway.app",
]
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'coach',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Emits the Content-Security-Policy header on every response (django-csp).
    "csp.middleware.CSPMiddleware",
]


ROOT_URLCONF = 'Uccharon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'coach' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Uccharon.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=not DEBUG,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Dhaka'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "coach" / "static"
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use WhiteNoise's compressed + hashed storage for cache-busting and gzip/brotli
# in production. This is the Django 5.x STORAGES-style config (replaces the
# older STATICFILES_STORAGE setting).
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Cache — backs the rate limiter (coach/ratelimit.py).
# Defaults to a local per-process cache, which enforces limits per worker. For
# strict global limits across multiple workers/instances set REDIS_URL (or swap
# in another shared backend) so all workers share one counter store.
REDIS_URL = os.getenv("REDIS_URL")
if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "uccharon-ratelimit",
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Session settings
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days
SESSION_SAVE_EVERY_REQUEST = True

# Login redirect
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'

# Security settings that only make sense once DEBUG is False (production).
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 7  # 1 week, raise once confirmed working
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# ─── Content Security Policy (django-csp) ────────────────────────────────
# A strict CSP is the key second line of defense against XSS. Because all AI
# provider API keys live in the browser's localStorage, a successful script
# injection would let an attacker exfiltrate those keys — so we lock down where
# scripts may come from and where the page may connect.
#
# Design:
#   • script-src: only our own origin + a per-request nonce + the Chart.js CDN.
#     No 'unsafe-inline', so injected <script> tags and inline handlers can't
#     execute. Our own inline <script> blocks carry the request nonce.
#   • connect-src: our origin + the four AI provider API domains the browser
#     talks to directly (Gemini, Groq, OpenRouter, OpenAI). Anything else (e.g.
#     an attacker's exfiltration endpoint) is blocked.
#   • style-src: allows 'unsafe-inline' because the UI uses many inline style=""
#     attributes and JS-generated inline styles. Style injection cannot read or
#     exfiltrate localStorage, so this is a deliberate, low-risk trade-off.
#   • object-src/base-uri/frame-ancestors locked down to blunt other vectors.
#   • img-src includes data: for inline SVG/PNG data URIs; worker-src/manifest-src
#     keep the PWA service worker and manifest working.
AI_PROVIDER_ORIGINS = [
    "https://generativelanguage.googleapis.com",  # Gemini
    "https://api.groq.com",                        # Groq
    "https://openrouter.ai",                       # OpenRouter
    "https://api.openai.com",                      # OpenAI (Whisper + chat)
]

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": [SELF],
        "script-src": [SELF, NONCE, "https://cdn.jsdelivr.net"],
        "style-src": [SELF, "'unsafe-inline'", "https://fonts.googleapis.com"],
        "font-src": [SELF, "https://fonts.gstatic.com"],
        "img-src": [SELF, "data:"],
        "connect-src": [SELF] + AI_PROVIDER_ORIGINS,
        "worker-src": [SELF],
        "manifest-src": [SELF],
        "object-src": [NONE],
        "base-uri": [SELF],
        "frame-ancestors": [NONE],
        "form-action": [SELF],
    },
}


